### PR TITLE
fix(byteparser): handle lddw relocations targeting .data.rel.ro

### LINKED ISSUE #25: another relocation in lddw is not in .rodata error
https://github.com/sonicfromnewyoke/linker-llm-mismatch

### PR DESCRIPTION
**Pull request by 0xull**
The fix extends the `ro_sections` predicate to also match
`.data.rel.ro*`. The `.data.rel.ro*` section is read-only after load-time pointer patching and can be 
an `lddw` relocation target just like `.rodata*`. This is sufficient as the symbol loop, gap-fill pass,
and `rodata_table` all operate over `ro_sections` and require no further
changes if `.data.rel.ro*` ever needs gap-filling.

I verified against the reproduction case in
https://github.com/sonicfromnewyoke/linker-llm-mismatch with a clean build.

A couple of naming questions:

`ro_sections` and `rodata_table` now cover sections that are not strictly
rodata. The names still make sense as shorthand but are no longer precise.
Is it worth renaming them to something like `const_sections` and
`const_table` to reflect that the actual criterion is "read-only from the
program's perspective and a valid lddw target", not "named .rodata"?

Relatedly, the gap-fill pass names synthetic entries with the prefix
`.rodata.__anon_` regardless of which section the gap belongs to. If a
gap were ever found inside `.data.rel.ro`, the label would read
`.rodata.__anon_7_0x0` (cosmetically wrong but functionally harmless
since the name is only ever used as a lookup key). Do we leave it given it has no runtime
effect or fix the format string to use the actual section name?

Fixes #25

### CODE REVIEW

File: tests/assembly/data_rel_ro_lddw.rs [hunk 1]
```diff
@@ -0,0 +1,57 @@
+// assembly-output: ptx-linker
+// revisions: two_sites
```
Comment (clairechingching) [inline tests/assembly/data_rel_ro_lddw.rs]: you don't need revision, since there's just one scenario you're testing

**Review by clairechingching — COMMENTED** [review]
good job!

File: tests/assembly/data_rel_ro_lddw.rs (hunk 1 above)
Comment (0xull) [reply tests/assembly/data_rel_ro_lddw.rs]: thank you, revised the test.

**Comment by clairechingching** [comment]
nice! sorry missed your question, imo no need to rename since in the context of svm, there's only the `.rodata` section. merggggggging!
