### PR TITLE
fix: resolve call relocations targeting anonymous .text.unlikely. section symbols

### LINKED ISSUE #26: sbpf-linker panics with "Identifier '' should have been resolved earlier" on some call relocations
# Problem

Current upstream/master of sbpf-linker fails to link some valid BPF objects with a panic:
```
thread 'main' panicked at .../sbpf-common-0.1.8/src/instruction.rs:150:17:
internal error: entered unreachable code: Identifier '' should have been resolved earlier
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: sbpf_common::instruction::Instruction::to_bytes
   3: sbpf_assembler::astnode::ASTNode::bytecode
   4: sbpf_assembler::section::SectionType::bytecode
   5: sbpf_assembler::program::Program::emit_bytecode
   6: sbpf_linker::link_program
   7: sbpf_linker::main

```
...

# Repro Context
I hit this while compiling[ upstream-vault](https://github.com/blueshift-gg/quasar/tree/master/examples/upstream-vault) with sbpf-linker built from source.

The important part is the linked object contains R_BPF_64_32 call relocations targeting .text.unlikely.:
Relocations [
  Section (3) .rel.text {
    0x230 R_BPF_64_64 .rodata
    0x268 R_BPF_64_64 .rodata
    0x3D8 R_BPF_64_64 .rodata
    0x428 R_BPF_64_64 .rodata
    0x650 R_BPF_64_32 .text.unlikely.
    0x1768 R_BPF_64_64 .rodata
    0x1840 R_BPF_64_32 .text.unlikely.
  }
]

---

I tested with the published sbpf-linker 0.1.8 installed from crates.io and it succeeds for the same workload:

From inspection, current upstream/master contains this call relocation handling in src/byteparser.rs:
```rust
} else if node.opcode == Opcode::Call {
    node.imm = Some(Either::Left(
        symbol.name().unwrap().to_owned(),
    ));
}
```
The crates.io sbpf-linker 0.1.8 source does not contain that Opcode::Call relocation branch.

# Suspected Cause
The current call relocation logic appears to assume that a CALL relocation target can always be resolved via symbol.name().
That does not seem to hold for section-symbol call relocations such as .text.unlikely.. In that case, the generated identifier appears to end up empty, and later sbpf_common::instruction::Instruction::to_bytes panics on:
Identifier '' should have been resolved earlier

# Additional Note
src/byteparser.rs also appears to only model .text, while the failing call relocations point into .text.unlikely.. So there may be a broader issue around handling multiple executable text sections, not just the panic itself.

### PR DESCRIPTION
**Pull request by 0xull**
R_BPF_64_32 call relocations into `.text.unlikely.` reference the
`STT_SECTION` symbol for that section rather than a named function
symbol. `symbol.name()` on a `STT_SECTION` symbol returns an empty
string, which was written as the call target label and caused
`emit_bytecode` to panic with `"Identifier '' should have been
resolved earlier"`.

Two changes: the symbol loop now registers labels for any `.text*`
section, not just `.text`, so cold functions in `.text.unlikely.` are
visible to the assembler. The call relocation handler now detects
an empty symbol name, falls back to a secondary lookup of
`obj.symbols()` using `(section_index, addend)` to find the named
function at that address, and uses that name as the label. If no
named symbol is found the raw integer immediate is left in place.

Fixes #26

### CODE REVIEW

File: src/byteparser.rs
Comment (clairechingching) [inline src/byteparser.rs:52]: i realize the assumption here is `STT_SECTION` symbols has zero size, right? then i prefer we filter out symbols of STT_SECTION type and add an assert right after to make sure non `STT_SECTION` symbols all have > 0 size

File: src/byteparser.rs [hunk 1]
```diff
@@ -201,7 +202,7 @@ pub fn parse_bytecode(bytes: &[u8]) -> Result<ParseResult, SbpfLinkerError> {
 
             // handle relocations
             for rel in section.relocations() {
-                // only handle relocations for symbols in the .rodata section for now
+                // handle relocations for rodata (lddw) and call targets
```
Comment (clairechingching) [inline src/byteparser.rs]: // handle relocations for call targets and rodata referenced by lddw

File: src/byteparser.rs [hunk 2]
```diff
@@ -230,9 +228,37 @@ pub fn parse_bytecode(bytes: &[u8]) -> Result<ParseResult, SbpfLinkerError> {
                         panic!("relocation in lddw is not in .rodata");
                     }
                 } else if node.opcode == Opcode::Call {
-                    node.imm = Some(Either::Left(
-                        symbol.name().unwrap().to_owned(),
-                    ));
+                    let name = symbol.name().unwrap_or("");
+                    if !name.is_empty() {
```
Comment (clairechingching) [inline src/byteparser.rs]: likewise, 

```
if STT_SECTION target {
    // STT_SECTION handling
} else {
    assert!(!name.is_empty())
    node.imm = Some(Either::Left(name.to_owned()));
}
```

**Review by clairechingching — COMMENTED** [review]
great job! just few small nits to tighten up the handling

File: src/byteparser.rs
Comment (0xull) [reply src/byteparser.rs:52]: Right, better approach. Thanks Claire!

**Comment by BretasArthur1** [comment]
Thx @0xull it fixed the issue in the compilation of upstream-vault

**Review by BretasArthur1 — APPROVED** [review]
lgtm

**Comment by 0xull** [comment]
> Thx @0xull it fixed the issue in the compilation of upstream-vault

That's good to hear! Thank you @BretasArthur1!
